# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nanblog
email: robmont2425@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Nan, This is my Code::Blog (he, did you see my pun there?).
  Here I'll post my experiments (in fact, this blog is one), among other
  things I found interesting. Enjoy.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nanmon.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  nanmon

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      autor: "Nan"
      preview: "Real agasajo"
